### ISSUE TITLE
spec-v3, grid view does not seem to work

### ISSUE THREAD

**Issue by martinschorb** [mobie/zebrafish-lm-project#12]
Hi,

I only get a black viewer for the grid view. The grey source outlines in the navigator (top left) are shown, but nothing else.

This is current Beta, MacOS

**Comment by tischi** [comment]
I tried:

```
new MoBIE("https://github.com/mobie/zebrafish-lm-datasets", MoBIESettings.settings().gitProjectBranch( "mobie3" ).view( "small-grid-view" ) );
```

And it seems that this view wants to load two additional tables, namely:

- https://raw.githubusercontent.com/mobie/zebrafish-lm-datasets/mobie3/data/membrane/tables/membrane-08B96BE794_lynEGFP_seg/shape_CFOR_pca_measured.tsv
- https://raw.githubusercontent.com/mobie/zebrafish-lm-datasets/mobie3/data/membrane/tables/membrane-08B96BE794_lynEGFP_seg/shape_TFOR_pca_measured.tsv

They have the same column names and thus it is crashing.

**Comment by tischi** [comment]
@constantinpape will have a look.

**Comment by tischi** [comment]
```
new MoBIE("https://github.com/mobie/zebrafish-lm-datasets", MoBIESettings.settings().gitProjectBranch( "mobie3" ).view( "small-grid-view" ) );
```

Works now.

@martinschorb can we close this issue or are there other problems?
