### ISSUE TITLE
grid view not working in spec-v2

### ISSUE THREAD

**Issue by tischi** [mobie/zebrafish-lm-project#8]
@constantinpape the grid views don't work yet in `spec-v2` (all images are rendered on top of each other). Maybe the JSON are not yet up to date?

**Comment by constantinpape** [comment]
Ok, I will double check this. Is MoBIE-beta up-to-date for me to try this out?

**Comment by tischi** [comment]
I updated MoBIE-beta. In fact. this was still quite old as we did not use `mobie-io` yet, but now it should work...does it?

**Comment by constantinpape** [comment]
Opening the project does not work at all due to issues with the transformedGrid, see https://github.com/mobie/mobie-viewer-fiji/issues/510. I think this is an issue on the MoBIE-Fiji side, so I am closing this one in favor of the issue in MoBIE-fiji.
